#! /bin/bash

## Help message when no parameter is provide.
if [ $# -ne 1 ]
then
   echo "Usage: bash annieARNyouokey <params_file>"
   echo ""
   echo "params.file: Input file with the parameters" 
   echo "an example of input file can be found in the test folder"
   exit
fi

##Reading in parameter file.
PARAMS=$1

echo ""
echo "======================="
echo "| LOADING PARAMETERS: |"
echo "======================="
echo ""

INSDIR=$(grep installation_directory: $PARAMS | awk '{ print $2 }')
echo "Installation directory = $INSDIR"
WD=$(grep working_directory: $PARAMS | awk '{ print $2 }')
echo "Working directory = $WD"
EXP=$(grep experiment_name: $PARAMS | awk '{ print $2 }')
echo "Experiment name = $EXP"
NUMSAMPLES=$(grep number_samples: $PARAMS | awk '{ print $2 }')
echo "Number of samples = $NUMSAMPLES"
GENOME=$(grep path_genome: $PARAMS | awk '{ print $2 }')
echo "Reference genome = $GENOME"
ANNOT=$(grep path_annotation: $PARAMS | awk '{ print $2 }')
echo "Genome Annotation = $ANNOT"
DESING=$(grep experimental_desing: $PARAMS | awk '{ print $2}')
echo="Experimental desing = $DESING"

i=0
SAMPLES=()
while [ $i -lt $NUMSAMPLES ]
do
   j=$(($i + 1))
   SAMPLES[$i]=$(grep path_sample_$j: $PARAMS | awk '{ print $2 }')
   ((i++))
done

echo "Samples = "
echo ${SAMPLES[@]}

## Generating work space.
echo ""
echo "=========================="
echo "| CREATING WORKING SPACE |"
echo "=========================="
echo ""

cd $WD
mkdir $EXP
cd $EXP
mkdir genome annotation samples results
cd genome
cp $GENOME genome.fa
cd ../annotation
cp $ANNOT annotation.gtf

##Generating reference genome index:
extract_splice_sites.py annotation.gtf > annot_splice.ss
extract_exons.py annotation.gtf > annot_exons.exon

cd ../genome
hisat2-build --ss ../annotation/annot_splice.ss --exon ../annotation/annot_exons.exon genome.fa index

echo "Index done!!"

cd ../samples

i=1
while [ $i -le $NUMSAMPLES ]
do
   mkdir sample_$i
   cd sample_$i
   j=$(($i - 1))
   cp ${SAMPLES[$j]} sample_$i.fq.gz
   cd ..
   ((i++))
done

echo "Samples charged!!"

cd ../results

i=1
while [ $i -le $NUMSAMPLES ]
do
   bash $INSDIR/AnnieARNyouOkey/rna_sample_processing $WD/$EXP/samples/sample_$i $i $NUMSAMPLES $INSDIR $DESIGN
   ((i++))
done

echo "Samples have been correctly processed!"

# Merging.

#bash $INSDIR/AnnieARNyouOkey/transcriptome_merging $SAMPLE_DIR/../../results $INS_DIR $DESIGN




